-- ════════════════════════════════════════════
-- DESPY — Migration : Alerte Secteur (carte des arnaques)
-- Signalements communautaires localisés + abonnements aux alertes de zone.
-- À exécuter une fois dans l'éditeur SQL Supabase.
-- ════════════════════════════════════════════

-- Signalements de fraude locale (contenu TOUJOURS modéré avant publication).
-- Vie privée : granularité commune uniquement (jamais d'adresse), la
-- description est réécrite par l'IA pour retirer tout nom/coordonnée.
CREATE TABLE IF NOT EXISTS fraud_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_email TEXT NOT NULL,          -- compte Despy (jamais affiché publiquement)
  category    TEXT NOT NULL,             -- faux_artisan | faux_agent | demarchage_abusif | arnaque_telephone | faux_livreur | vol_ruse | autre
  description TEXT,                      -- version MODÉRÉE (sans nom/adresse/téléphone)
  ville       TEXT NOT NULL,
  code_postal TEXT NOT NULL,
  lat         DOUBLE PRECISION,          -- centre de la commune (geo.api.gouv.fr)
  lng         DOUBLE PRECISION,
  status      TEXT DEFAULT 'pending',    -- pending → approved | rejected
  confidence  REAL,                      -- confiance de la modération IA
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_fraud_reports_status ON fraud_reports (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_fraud_reports_cp ON fraud_reports (code_postal);

-- Abonnements aux alertes de zone.
-- Gratuit : récap hebdomadaire de SA commune. Premium (clients.subscribed) :
-- notification immédiate (push + email) sur tout le département.
CREATE TABLE IF NOT EXISTS fraud_alert_subs (
  email       TEXT PRIMARY KEY,
  ville       TEXT,
  code_postal TEXT NOT NULL,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_fraud_subs_cp ON fraud_alert_subs (code_postal);
