-- ════════════════════════════════════════════
-- DESPY — Migration : Privacy Cleanup
-- Table des demandes (remplie par privacy-request.js, lue par privacy-status.js).
-- À exécuter une fois dans l'éditeur SQL Supabase.
-- (Si la table existe déjà, les IF NOT EXISTS rendent le script sans danger.)
-- ════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS privacy_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email   TEXT NOT NULL,
  prenom       TEXT,
  nom          TEXT,
  target_email TEXT,
  phone        TEXT,
  ville        TEXT,
  status       TEXT DEFAULT 'pending',   -- pending → in_progress → done
  notes        TEXT,                     -- sites traités, dates d'envoi des demandes RGPD
  activated_at TIMESTAMPTZ DEFAULT NOW(),
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_privacy_requests_email ON privacy_requests (user_email);

-- Colonne notes si la table existait déjà sans elle
ALTER TABLE privacy_requests ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE privacy_requests ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending';

-- Journal des demandes RGPD envoyées automatiquement (privacy-dispatch.js)
-- Une ligne par broker contacté → le suivi de l'espace client devient réel.
CREATE TABLE IF NOT EXISTS privacy_dispatch_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email  TEXT NOT NULL,
  broker_id   TEXT NOT NULL,
  broker_name TEXT,
  status      TEXT DEFAULT 'sent',      -- sent → confirmed (quand le broker répond)
  sent_at     TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_privacy_dispatch_email ON privacy_dispatch_log (user_email);

-- Trouvailles de l'agent de scan (privacy-scan.js) — stockage minimal :
-- URL + catégorie + action recommandée. Pas de contenu de page.
CREATE TABLE IF NOT EXISTS privacy_findings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT NOT NULL,
  url        TEXT NOT NULL,
  title      TEXT,
  category   TEXT,              -- annuaire | reseau_social | presse_blog | donnees_legales | homonyme_probable | autre
  action     TEXT,              -- formulaire | rgpd_email | guide_client | humain | rien
  confidence REAL,
  reason     TEXT,
  status     TEXT DEFAULT 'found',  -- found → treated → verified
  found_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_privacy_findings_email ON privacy_findings (user_email);
